# Production Error Handling

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

# Production Security

server.forward-headers-strategy=framework

# Production Database

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Production Logging

logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.security=WARN